export const Description =
  'Welcome to Payslate. Dotmite Technologies Private Limited ("us", "we", or "our") operates the Payslate platform, including its web and mobile applications (hereinafter referred to as the "Service"). This Privacy Policy explains how we collect, use, disclose, and protect your information when you use our Service and describes your choices regarding the collection and use of your information.';

export const DefinitionsList = [
  "Personal Data: Data about a living individual who can be identified from those data.",
  "Usage Data: Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.",
  "Cookies: Small pieces of data stored on your device (computer or mobile device).",
];

export const PersonalData: string[] = [
  "Email Address",
  "Phone Number",
  "Business Name",
  "First and Last Name",
  "Cookies and Usage Data collected automatically",
];

export const UsageData: string[] = [
  "Your computer's Internet Protocol (IP) address",
  "Browser type and version",
  "Pages of our Service you visit",
  "Time and date of your visit",
  "Time spent on pages",
  "Unique device identifiers",
  "Diagnostic data",
];

export const MobileDeviceData: string[] = [
  "Mobile device type",
  "Unique mobile ID",
  "Mobile operating system",
  "Type of mobile Internet browser",
  "Diagnostic data",
];

export const DotmiteTechnologiesData: string[] = [
  "Provide and maintain our Service.",
  "Notify you about changes to our Service.",
  "Allow you to participate in interactive features.",
  "Provide customer support.",
  "Gather analysis to improve our Service.",
  "Monitor the usage of our Service.",
  "Detect, prevent, and address technical issues.",
  "Provide you with updates about new features and services unless you opt-out.",
];

export const RetentionDataDescription =
  "We retain Personal Data only as long as necessary to fulfill the purposes outlined in this Privacy Policy, comply with legal obligations, resolve disputes, and enforce agreements. Usage Data is retained for a shorter period unless required for security or functionality enhancements.";

export const TransferDataDescription =
  "Your information may be transferred to and maintained on servers located outside your jurisdiction. By providing your information, you consent to such transfers, ensuring adequate security controls are in place.";

export const ShareDataDescription =
  "If Dotmite Technologies Private Limited is involved in a merger, acquisition, or asset sale, your Personal Data may be transferred. We will notify you before such changes occur.";

export const LegalRequirementsDescription =
  "Dotmite Technologies Private Limited may disclose your Personal Data in good faith if necessary to:";

export const LegalRequirementsData: string[] = [
  "Comply with legal obligations.",
  "Protect and defend our rights or property.",
  "Prevent or investigate possible wrongdoing.",
  "Protect the personal safety of users or the public.",
  "Protect against legal liability.",
];

export const SecurityDataDescription =
  "We prioritize the security of your data using commercially acceptable means, but no method of transmission over the Internet or electronic storage is 100% secure. While we strive to protect your data, absolute security cannot be guaranteed.";

export const ServiceProvidersData: string[] = [
  "Facilitate our Service.",
  "Provide the Service on our behalf.",
  "Perform Service-related tasks.",
  "Assist in analyzing how our Service is used.",
];

export const AnalyticsDescription =
  "We may use third-party services such as Google Analytics to track and report Service usage. To opt out of Google Analytics, you can use the Google Analytics opt-out browser add-on.";

export const ChildrenPrivacyDescription =
  "Payslate does not knowingly collect personal information from individuals under the age of 18. If we learn we have collected data from a child under 18 without parental consent, we will delete it. Contact us at support@dotmite.com if you believe this has occurred.";

export const UserRightsData: string[] = [
  "Access, update, or delete your Personal Data.",
  "Restrict or object to the processing of your data.",
  "Withdraw consent where processing is based on consent.",
  "File a complaint with your local data protection authority.",
];

export const ChangesPrivacyPolicyDescription =
  'We may update this Privacy Policy from time to time. We will notify you of changes by posting the new Privacy Policy on this page and updating the "Effective Date." Check this page periodically for updates.';
