const DefinitionsList = [
  "Personal Data: Data about a living individual who can be identified from those data.",
  "Usage Data: Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.",
  "Cookies: Small pieces of data stored on your device (computer or mobile device).",
];

const PersonalData = [
  "Email Address",
  "Phone Number",
  "Business Name",
  "First and Last Name",
  "Cookies and Usage Data collected automatically",
];

const UsageData = [
  "Your computer's Internet Protocol (IP) address",
  "Browser type and version",
  "Pages of our Service you visit",
  "Time and date of your visit",
  "Time spent on pages",
  "Unique device identifiers",
  "Diagnostic data",
];

const MobileDeviceData = [
  "Mobile device type",
  "Unique mobile ID",
  "Mobile operating system",
  "Type of mobile Internet browser",
  "Diagnostic data",
];

const DotmiteTechnologiesData = [
  "Provide and maintain our Service.",
  "Notify you about changes to our Service.",
  "Allow you to participate in interactive features.",
  "Provide customer support.",
  "Gather analysis to improve our Service.",
  "Monitor the usage of our Service.",
  "Detect, prevent, and address technical issues.",
  "Provide you with updates about new features and services unless you opt-out.",
];

const LegalRequirementsData = [
  "Comply with legal obligations.",
  "Protect and defend our rights or property.",
  "Prevent or investigate possible wrongdoing.",
  "Protect the personal safety of users or the public.",
  "Protect against legal liability.",
];

const ServiceProvidersData = [
  "Facilitate our Service.",
  "Provide the Service on our behalf.",
  "Perform Service-related tasks.",
  "Assist in analyzing how our Service is used.",
];

const UserRightsData = [
  "Access, update, or delete your Personal Data.",
  "Restrict or object to the processing of your data.",
  "Withdraw consent where processing is based on consent.",
  "File a complaint with your local data protection authority.",
];

const AnalyticsDescription =
  "We may use third-party services such as Google Analytics to track and report Service usage. To opt out of Google Analytics, you can use the Google Analytics opt-out browser add-on.";

const RetentionDataDescription =
  "We retain Personal Data only as long as necessary to fulfill the purposes outlined in this Privacy Policy, comply with legal obligations, resolve disputes, and enforce agreements. Usage Data is retained for a shorter period unless required for security or functionality enhancements.";

const TransferDataDescription =
  "Your information may be transferred to and maintained on servers located outside your jurisdiction. By providing your information, you consent to such transfers, ensuring adequate security controls are in place.";

const ShareDataDescription =
  "If Dotmite Technologies Private Limited is involved in a merger, acquisition, or asset sale, your Personal Data may be transferred. We will notify you before such changes occur.";

const LegalRequirementsDescription =
  "Dotmite Technologies Private Limited may disclose your Personal Data in good faith if necessary to:";

const SecurityDataDescription =
  "We prioritize the security of your data using commercially acceptable means, but no method of transmission over the Internet or electronic storage is 100% secure. While we strive to protect your data, absolute security cannot be guaranteed.";

const ChildrenPrivacyDescription =
  "Payslate does not knowingly collect personal information from individuals under the age of 18. If we learn we have collected data from a child under 18 without parental consent, we will delete it. Contact us at support@dotmite.com if you believe this has occurred.";

const ChangesPrivacyPolicyDescription =
  'We may update this Privacy Policy from time to time. We will notify you of changes by posting the new Privacy Policy on this page and updating the "Effective Date." Check this page periodically for updates.';

export const PrivacyHeader = {
  label: "Payslate",
  heading: "Privacy Policy",
  date: " Effective January 10, 2026",
};

export const Description =
  'Welcome to Payslate. Dotmite Technologies Private Limited ("us", "we", or "our") operates the Payslate platform, including its web and mobile applications (hereinafter referred to as the "Service"). This Privacy Policy explains how we collect, use, disclose, and protect your information when you use our Service and describes your choices regarding the collection and use of your information.';

export const PRIVACY_POLICY_DATA = [
  {
    id: 1,
    heading: "Definitions",
    data: [
      {
        type: "List",
        listType: "ul",
        data: DefinitionsList,
      },
    ],
  },
  {
    id: 2,
    heading: "Information We Collect and Its Use",
    data: [
      {
        type: "Paragraph",
        data: "Information You Provide Directly",
      },
      {
        type: "Paragraph",
        data: "While using our Service, we may ask you to provide certain personally identifiable information, including but not limited to:",
      },
      {
        type: "List",
        listType: "ul",
        data: PersonalData,
      },
    ],
  },
  {
    id: 3,
    heading: "Usage Data",
    data: [
      {
        type: "Paragraph",
        data: "We may also collect information automatically when you use our Service, such as:",
      },
      {
        type: "List",
        listType: "ul",
        data: UsageData,
      },
    ],
  },
  {
    id: 4,
    heading:
      "When accessing the Service through a mobile device, this Usage Data may include:",
    data: [
      {
        type: "List",
        listType: "ul",
        data: MobileDeviceData,
      },
    ],
  },
  {
    id: 5,
    heading: "Cookies Information",
    data: [
      {
        type: "Paragraph",
        data: "We use cookies and similar tracking technologies to monitor activity on our Service and store certain information. You can control cookie preferences through your browser settings, but some parts of the Service may not function properly if you disable cookies.",
      },
    ],
  },
  {
    id: 6,
    heading: "Dotmite Technologies Private Limited uses the collected data to:",
    data: [
      {
        type: "List",
        listType: "ol",
        data: DotmiteTechnologiesData,
      },
    ],
  },
  {
    id: 7,
    heading: "Retention of Data",
    data: [
      {
        type: "Paragraph",
        data: RetentionDataDescription,
      },
    ],
  },
  {
    id: 8,
    heading: "Transfer of Data",
    data: [
      {
        type: "Paragraph",
        data: TransferDataDescription,
      },
    ],
  },
  {
    id: 9,
    heading: "Who You May Choose to Share Your Data With",
    data: [
      {
        type: "Paragraph",
        data: ShareDataDescription,
      },
    ],
  },
  {
    id: 10,
    heading: "Disclosure for Legal Requirements",
    data: [
      {
        type: "Paragraph",
        data: LegalRequirementsDescription,
      },
      {
        type: "List",
        listType: "ul",
        data: LegalRequirementsData,
      },
    ],
  },
  {
    id: 11,
    heading: "Security of Data",
    data: [
      {
        type: "Paragraph",
        data: SecurityDataDescription,
      },
    ],
  },
  {
    id: 12,
    heading: "Service Providers",
    data: [
      {
        type: "Paragraph",
        data: "We may employ third-party companies to:",
      },
      {
        type: "List",
        listType: "ul",
        data: ServiceProvidersData,
      },
      {
        type: "Paragraph",
        data: "These third parties only have access to your Personal Data for these tasks and are obligated not to disclose or use it for other purposes.",
      },
    ],
  },
  {
    id: 13,
    heading: "Analytics",
    data: [
      {
        type: "Paragraph",
        data: AnalyticsDescription,
      },
    ],
  },
  {
    id: 14,
    heading: "Children's Privacy",
    data: [
      {
        type: "Paragraph",
        data: ChildrenPrivacyDescription,
      },
    ],
  },
  {
    id: 15,
    heading: "Your Privacy Rights",
    data: [
      {
        type: "Paragraph",
        data: "You have the right to:",
      },
      {
        type: "List",
        listType: "ul",
        data: UserRightsData,
      },
    ],
  },
  {
    id: 16,
    heading: "Changes to This Privacy Policy",
    data: [
      {
        type: "Paragraph",
        data: ChangesPrivacyPolicyDescription,
      },
    ],
  },
  {
    id: 17,
    heading: "Contact Us",
    data: [
      {
        type: "Paragraph",
        data: "For questions or concerns about this Privacy Policy, contact us at:",
      },
      {
        type: "Paragraph",
        data: "Email: support@dotmite.com",
      },
    ],
  },
];
