name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Dependencies
      run: npm install

    - name: Lint Code
      run: npm run lint

    - name: Build Application
      run: npm run build

    - name: Security Scan (npm audit)
      run: npm audit --audit-level=high || true

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy
      run: |
        ssh ubuntu@13.203.132.99 << 'EOF'
        cd ~/payslate/payslate-website
        git pull origin main
        npm install
        npm run build
        pm2 restart payslate-website
        EOF


